[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    # Enable HTTPS strict transport security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options = "nosniff"
    
    # Block site from being framed with X-Frame-Options
    X-Frame-Options = "DENY"
    
    # Comprehensive Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdnjs.buymeacoffee.com https://www.googletagmanager.com https://*.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com;
      frame-src https://www.googletagmanager.com https://www.buymeacoffee.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''
    
    # Cross-site scripting protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), screen-wake-lock=(), ambient-light-sensor=(), accelerometer=(), gyroscope=(), magnetometer=(), midi=(), sync-xhr=(), autoplay=(), display-capture=()"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[redirects]]
  from = "/_astro/*.css"
  to = "/_astro/:splat.css"
  status = 200
  force = false

[[redirects]]
  from = "/_astro/index.Dif9_gxa.css"
  to = "/dist/_astro/index.Dif9_gxa.css"
  status = 200
  force = false

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect all HTTP to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Security.txt file for security researchers
[[redirects]]
  from = "/.well-known/security.txt"
  to = "/security.txt"
  status = 301

# Prevent access to sensitive files
[[headers]]
  for = "/.env"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Content-Type = "text/plain" 